env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:flowtype-errors/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  GlobalData: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - flowtype
  - flowtype-errors
rules:
  indent: [error, 4, { SwitchCase: 1 }]
  no-unused-vars: [error, {
    args: none,
    varsIgnorePattern: "^(_|React$)",
  }]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]
  react/jsx-uses-vars: error
  flowtype/require-valid-file-annotation: [error, always]
  flowtype/delimiter-dangle: [error, always]
  flowtype/no-weak-types: [2, { any: true }]
